### ISSUE TITLE
Create Author Portal

### ISSUE THREAD

**Issue by mhhoban** [mhhoban/skribblr#2]
# Create Author Portal
## View for author to log in and compose an entry to publish

Sub Tasks:
- [x] Create Author Portal View ( #6 )

- [x] Create Author Portal Interface ( #7 )

- [x] Create Compose Function ( #8 )

- [x] Create List of Prior Posts from which to edit posts ( #9 )

- [x] Create Delete entry functionality ( #16 )
