### ISSUE TITLE
Create Author Portal - Create Compose Function

### ISSUE THREAD

**Issue by mhhoban** [mhhoban/skribblr#8]
# Create Compose Function for #2 

### Tasks:
- [x] Add view method for adding new Entry model to db
- [x] create template for composing new Entry
- [x] connect template to view method
- [x] connect template to portal home
