### ISSUE TITLE
Create Author Portal - Create Edit Post Function

### ISSUE THREAD

**Issue by mhhoban** [mhhoban/skribblr#9]
# Create Edit Post functionality for #2 

### Tasks:
- [x] create template for list of previous posts, connect to portal home
- [x] create template for editing post
- [x] create code for loading entry data from db to editing template
- [x] method for updating db data from template
